services:

  rabbitmq:
    ports:
      - 127.0.0.1:${COMPOSE_PROJECT_PORT}:5672 # AMQP
      - 127.0.0.1:${COMPOSE_PROJECT_APP_PORT}:15672 # Management UI
    networks:
      net: {}

networks:
  net:
    driver: bridge
    external: true
    name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_CNET}
  default:
    external: true
    name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_CNET}