services:

  mailer:
    ports:
      - "1217.0.0.1:${COMPOSE_PROJECT_PORT:-1025}:1025"     # SMTP port — send your app mails here
      - "1217.0.0.1:${COMPOSE_PROJECT_APP_PORT:-8025}:8025" # Web UI + API
    networks:
      net: {}

networks:
  net:
    driver: bridge
    external: true
    name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_CNET}
  default:
    external: true
    name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_CNET}